CREATE DATABASE CAFE_MANAGEMENT
GO

USE CAFE_MANAGEMENT
GO


GO
CREATE TABLE [DANHMUC]
(
MaDanhMuc NVARCHAR(10) PRIMARY KEY,
TenDanhMuc NVARCHAR(30) NOT NULL,
)

GO

CREATE TABLE [THUCUONG]
(
MaThucUong NVARCHAR(10) PRIMARY KEY,
TenThucUong NVARCHAR(50) NOT NULL,
DanhMuc NVARCHAR(10) REFERENCES DANHMUC(MaDanhMuc) ,
DonGia INT NOT NULL,
SoLuong INT NOT NULL,
TrangThaiMon BIT,
UNIQUE(TenThucUong)
)
GO

CREATE TABLE [NHANVIEN]
(
	MaNhanVien NVARCHAR(10) PRIMARY KEY,
	TenNhanVien NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(20) NOT NULL,
	ChucVu NVARCHAR(30),
	NgaySinh DATE,
	SDT NVARCHAR(20) CHECK (SDT like '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	Luong INT,
	SoGioLamViec REAL,
	TrangThai INT,
)
GO

CREATE TABLE [LUONGMOITHANG]
(
	 MaNhanVien NVARCHAR(10) REFERENCES NHANVIEN(MaNhanVien) NOT NULL,
	 Thang INT NOT NULL,
	 Nam INT NOT NULL,
	 Luong INT,
	 TinhTrang BIT, -- Đã thanh toán 1, chưa thanh toán 0
)

CREATE TABLE [KHACHHANGTHANTHIET]
(
	SDT NVARCHAR(20) PRIMARY KEY CHECK (SDT like '0[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	TenKhachHang NVARCHAR(50) NOT NULL,
	DiemTichLuy INT ,
	TongChiTieu INT NOT NULL,
)
GO

CREATE TABLE [HOADON]
(
	MaHoaDon INT NOT NULL,
	NgayGio DATETIME NOT NULL,
	MaKhachHang NVARCHAR(20) REFERENCES KHACHHANGTHANTHIET(SDT)
	ON DELETE SET NULL
	ON UPDATE CASCADE,
	MaNhanVien NVARCHAR(10) REFERENCES NHANVIEN(MaNhanVien)
	ON DELETE SET NULL
	ON UPDATE CASCADE,
	TongHoaDon INT NOT NULL,
	GiamGia INT, 
	PRIMARY KEY (MaHoaDon,NgayGio)
)
GO

CREATE TABLE [CHITIETHOADON]
(
	MaHoaDon INT NOT NULL,
	NgayGio DATETIME NOT NULL,
	MaThucUong NVARCHAR(10) NOT NULL,
	DonGia INT NOT NULL,
	SoLuong INT NOT NULL,
	PRIMARY KEY (MaHoaDon, NgayGio, MaThucUong),
	FOREIGN KEY (MaThucUong) REFERENCES THUCUONG(MaThucUong) ,
	FOREIGN KEY (MaHoaDon,NgayGio) REFERENCES HOADON(MaHoaDon,NgayGio)
)
GO

CREATE TABLE [DOANHTHU]
(
	Ngay DATE PRIMARY KEY,
	DoanhThu int NOT NULL,
)
GO

DROP Table CHITIETHOADON
drop table HOADON
drop table NHANVIEN
drop table KHACHHANGTHANTHIET
drop table THUCUONG
drop table LUONGMOITHANG
alter table NhanVien add TrangThai INT

SELECT *FROM vi_NhanVienList

INSERT INTO HOADON VALUES (1, '2022/11/17', '0347892345', 'NV02',39000, 10000)
INSERT INTO HOADON VALUES (2, '2022/11/17', '0347892345', 'NV01',39000, 10000)
INSERT INTO HOADON VALUES (1, '2022/10/17', '0347892345', 'NV02',39000, 10000)
INSERT INTO HOADON VALUES (2, '2022/10/17', '0347892345', 'NV01',39000, 10000)
INSERT INTO CHITIETHOADON VALUES (1,'2022/11/17','M15',39000,1)
INSERT INTO CHITIETHOADON VALUES (2,'2022/11/17','M14',39000,1)
INSERT INTO CHITIETHOADON VALUES (1,'2022/10/17','M15',39000,1)
INSERT INTO CHITIETHOADON VALUES (2,'2022/10/17','M14',39000,1)
delete from HoaDon
select * from HoaDon


